{
    'name': 'LEARN',
    'version': '1.0.0',
    'category': 'Learn',
    'sequence': 1,
    'summary': '',
    'description': """""",
    'depends': ['web', 'stock', 'mrp'],
    'data': [],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'assets': {},
    'license': 'LGPL-3',
}